apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-dogstatsd-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-dogstatsd
  metrics:
  - type: External
    external:
      metricName: datadogmetric@default:flask-dogstatsd-metric
      targetAverageValue: 2
