apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-dogstatsd-metric
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-dogstatsd
  metrics:
  - type: External
    external:
      metricName: hello.world
      targetAverageValue: 6
