apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-requests
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-dogstatsd
  metrics:
  - type: External
    external:
      metricName: trace.flask.request.hits
      targetAverageValue: 6
