apiVersion: v1
kind: Secret
metadata:
  name: datadog-api-key
type: Opaque
data:
  api-key: ZWFiMmRlOWI3N2Y5ODA4ZjNkMGZjYzBjMDA5ZTcwM2E=
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-app-key
type: Opaque
data:
  app-key: Yjc2ZTM4ZTM4MGUzNDVlN2I2OWEyMDY1ODY1NTRlYTc1NmMyYWI1YQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-cluster-agent
type: Opaque
data:
  token: PFRoaXJ0eVgyWGNoYXJhY3RlcnNYbG9uZ1h0b2tlbj4=
