apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |-
    server {
      listen       80;
      server_name  localhost;
      location / {
        proxy_pass  http://localhost:5000/;
      }
    }
  status.conf: |-
    server {
      listen 81;
      server_name localhost;

      access_log off;
      allow all;

      location /nginx_status {
        stub_status;
      server_tokens on;
      }
    } 
