apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dogstatsd
  labels: 
    app: flask-dogstatsd
spec:
  selector:
    matchLabels: 
      app: flask-dogstatsd
  replicas: 2
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-dogstatsd
      annotations:
        ad.datadoghq.com/flask-dogstatsd.check_names: '["process"]'
        ad.datadoghq.com/flask-dogstatsd.init_configs: '[{}]'
        ad.datadoghq.com/flask-dogstatsd.instances: |
          [
            {
              "name": "flask",
              "search_string": ["/usr/local/bin/python", "/usr/local/bin/flask", "run"],
              "exact_match": "false"
            }
          ]
        ad.datadoghq.com/flask-dogstatsd.logs: '[{"source": "python", "service": "flask-dogstatsd"}]'
    spec:
      containers:
      - name: flask-dogstatsd
        image: gcr.io/<GCP_PROJECT_NAME>/flask-dogstatsd:latest
        imagePullPolicy: Always
        ports: 
          - containerPort: 5000
        env:
          - name: FLASK_ENV
            value: "production" 
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-dogstatsd-service
  labels: 
    app: flask-dogstatsd
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: flask-app-port
  selector: 
    app: flask-dogstatsd
  type: LoadBalancer 
