apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent
spec:
  type: ClusterIP
  selector:
    app: datadog-cluster-agent
  ports:
  - port: 5005
    name: agentport
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent-metrics-api
spec:
  type: ClusterIP
  selector:
    app: datadog-cluster-agent
  ports:
  - port: 8443
    name: metricsapi
    protocol: TCP
