apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-installinfo
  labels: {}
  annotations: {}
data:
  install_info: |
    ---
    install_method:
      tool: flask-dogstatsds
      tool_version: 1.0.0
      installer_version: 1.0.0
